apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  name: bao-hnatekmar-xyz
  namespace: crossplane-system
spec:
  forProvider:
    type: kubernetes
    path: kubernetes
  providerConfigRef:
    name: bao-hnatekmar-xyz
