apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: bao-hnatekmar-xyz
spec:
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: bao-hnatekmar-xyz
  providerConfigRef:
    name: sso-hnatekmar-xyz
  forProvider:
    accessType: CONFIDENTIAL
    clientId: bao-hnatekmar-xyz
    enabled: true
    realmId: master
    validRedirectUris:
      - https://bao.hnatekmar.xyz/ui/vault/auth/oidc/oidc/callback
      - http://localhost:8250/oidc/callback
