apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: local
spec:
  provider:
    vault:
      server: https://bao.hnatekmar.xyz
      path: "clusters"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
          role: "bao-hnatekmar-xyz"
