apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: algovectra-main
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: bao-hnatekmar-xyz
  forProvider:
    name: algovectra
    policy: |
      path "algovectra/data/*" {
        capabilities = ["create", "read", "update", "patch", "delete", "list", "scan"]
      }
      path "algovectra/metadata/*" {
        capabilities = ["create", "read", "update", "patch", "delete", "list", "scan"]
      }
