# Exposes the Kubernetes API using Kong
apiVersion: v1
kind: Service
metadata:
  name: k8s-oidc-proxy
  namespace: default
  annotations:
    konghq.com/protocol: "https"
spec:
  type: ExternalName
  externalName: kubernetes.default.svc
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-oidc-public
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Use the Kong Ingress Controller
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "false"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - k8s.hnatekmar.xyz
      secretName: k8s-oidc-tls-secret
  rules:
    - host: k8s.hnatekmar.xyz
      http:
        paths:
          - path: /.well-known/openid-configuration
            pathType: Exact
            backend:
              service:
                name: k8s-oidc-proxy
                port:
                  number: 443
          - path: /openid/v1/jwks
            pathType: Exact
            backend:
              service:
                name: k8s-oidc-proxy
                port:
                  number: 443
