# Default values for openbao.
# This is a YAML file that lists values that can be configured.
# For full list of available values, see the chart's README.

replicaCount: 1

# Additional configuration can be added here...

ui:
  enabled: true

server:
  affinity: ""
  ingress:
    enabled: true
    tls:
      - secretName: bao-secret
        hosts:
          - bao.hnatekmar.xyz
    hosts:
      - host: bao.hnatekmar.xyz
  image:
    repository: openbao/openbao
    tag: "latest"
    pullPolicy: IfNotPresent
  dataStorage:
    storageClass: "local-path"
  auditStorage:
    storageClass: "local-path"
