apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: bao-hnatekmar-xyz
spec:
  address: https://bao.hnatekmar.xyz
  credentials:
    source: Secret
    secretRef:
      name: openbao-hnatekmar-xyz
      namespace: crossplane-system
      key: config
