apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: bao-hnatekmar-xyz
spec:
  address: http://openbao.openbao-system.svc.cluster.local:8200
  credentials:
    source: Kubernetes
  role: vaultRole
