apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digitalocean
  namespace: crossplane-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: local-algovectra
    kind: ClusterSecretStore
  target:
    name: digitalocean
    template:
      # Json that looks like this { "token": "<token_from_secret>" }
      engineVersion: v2
      data:
        config: |
          {
            "token": "{{ .token }}",
          }
  data:
    - secretKey: token
      remoteRef:
        key: /algovectra/digitalocean
        property: token
---
apiVersion: digitalocean.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: digitalocean
spec:
  credentials:
    secretRef:
      key: config
      name: digitalocean
      namespace: crossplane-system
    source: Secret
